"""sf.action.skill_synthesizer — high-level synthesis around UniversalCodebook.

Wraps two minting paths the user actually cares about:

    1. **From description** (user-driven): user types
       "帮我每天 9 点打开股市行情" — embed it via the codebook's
       text encoder, query for similar existing skills, and either
       bump-and-return an existing match or mint a new L3 prototype.

    2. **From demonstration** (AI-driven): a successful action trace
       (sequence of L1 prototype ids) that just produced positive
       reward — synthesise as L2 (anonymous compound) or L3 (if
       a description has been generated by the agent).

Plus the bookkeeping bits the codebook itself stays unaware of:

    * Cosine-dedup before minting (cheap hash + similarity short-circuit)
    * Rate-limiting on user-driven mints (defends against cheap spam)
    * Hooks for ``intrinsic.SelfGoalProposer``: when a goal is
      proposed, mint a placeholder skill and let the trainer fill in
      the embedding via ``link_goal_to_skill``.
    * Monthly LTD pass (calls codebook.decay_unused + prune)

Two layers of prevention keep the codebook from exploding:

    * **Per-call dedup** in ``synthesize_from_description``: similarity
      > ``dedup_threshold`` to the nearest existing skill -> bump
      strength + return that id.
    * **Budgeted minting**: new mints are gated on a
      ``mints_per_minute`` budget for user-driven calls.
"""
from __future__ import annotations

import hashlib
import time
from collections import OrderedDict, deque
from dataclasses import dataclass
from typing import Callable, Deque, Iterable, List, Optional, Tuple

import torch

from .universal_codebook import (
    LAYER_L2,
    LAYER_L3,
    UniversalCodebook,
    default_text_encoder,
)


@dataclass
class SynthConfig:
    dedup_threshold: float = 0.92      # >= this -> bump existing instead of new
    user_mints_per_minute: int = 12    # cheap rate-limit on user-driven mints
    trace_min_len: int = 2
    trace_max_len: int = 16
    decay_days: int = 30
    auto_prune: bool = True
    success_strength_boost: float = 0.7
    failure_strength_boost: float = 0.4
    # LRU caps for the dedup caches.  Without these the per-text and
    # per-trace dicts grow unbounded over a long session and leak RAM.
    text_cache_max: int = 4096
    trace_cache_max: int = 4096


# ---------------------------------------------------------------------------
# SkillSynthesizer
# ---------------------------------------------------------------------------


class SkillSynthesizer:
    """High-level synthesis layer over ``UniversalCodebook``.

    Parameters
    ----------
    codebook : UniversalCodebook
        The lifelong codebook receiving mints.
    embed_fn : Callable[[str], torch.Tensor], optional
        Text-to-hidden embedder; defaults to the codebook's encoder.
        Override with a real sentence-transformer for production.
    skill_log : Any, optional
        Anything providing ``log_mint(pid, layer, desc, extra)`` /
        ``log_activate(pid, reward)`` / ``log_prune(pids, reason)``.
        ``skill_log_v2.SkillLog`` is the canonical implementation.
    cfg : SynthConfig, optional
        Tuning knobs.
    """

    def __init__(
        self,
        codebook: UniversalCodebook,
        embed_fn: Optional[Callable[[str], torch.Tensor]] = None,
        skill_log: Optional[object] = None,
        cfg: Optional[SynthConfig] = None,
    ) -> None:
        self.codebook = codebook
        self.embed_fn = embed_fn or codebook.text_encoder
        self.skill_log = skill_log
        self.cfg = cfg or SynthConfig()
        # rate-limit ring buffer (timestamps of recent user mints)
        self._user_mint_ts: Deque[float] = deque(maxlen=self.cfg.user_mints_per_minute * 4)
        # description -> proto_id cache so identical text is cheap.
        # OrderedDict gives us a cheap LRU when we manually move_to_end.
        self._text_cache: "OrderedDict[str, int]" = OrderedDict()
        # demo trace -> proto_id cache (idempotent demonstration)
        self._trace_cache: "OrderedDict[tuple, int]" = OrderedDict()

    def _cache_put(self, cache: "OrderedDict", key, value, max_size: int) -> None:
        """LRU insert.  Evicts oldest when over capacity."""
        if key in cache:
            cache.move_to_end(key)
        cache[key] = value
        while len(cache) > max_size:
            cache.popitem(last=False)

    def _cache_touch(self, cache: "OrderedDict", key):
        if key in cache:
            cache.move_to_end(key)
            return cache[key]
        return None

    # ------------------------------------------------------------------ user path

    def synthesize_from_description(
        self,
        description: str,
        urgency: float = 1.0,
    ) -> int:
        """Mint (or bump) a skill from a free-form user description.

        Returns the proto_id of the resulting (new or matched) skill,
        or ``-1`` if rate-limited and no near-match was found.
        """
        text = (description or "").strip()
        if not text:
            return -1

        # Cheap caches first.
        cached = self._cache_touch(self._text_cache, text)
        if cached is not None:
            self.codebook.activate(cached, reward=0.4 * urgency)
            return cached

        emb = self.embed_fn(text)
        if emb.numel() != self.codebook.hidden:
            raise ValueError(f"embed_fn returned dim {emb.numel()}, expected {self.codebook.hidden}")

        # Dedup against existing skills.
        hits = self.codebook.query(emb, top_k=1)
        if hits and hits[0][2] >= self.cfg.dedup_threshold:
            pid = hits[0][0]
            self.codebook.activate(pid, reward=0.5 * urgency)
            self._cache_put(self._text_cache, text, pid, self.cfg.text_cache_max)
            if self.skill_log is not None:
                self.skill_log.log_activate(pid, reward=0.5 * urgency)
            return pid

        # Rate-limit user-driven mints.
        now = time.time()
        cutoff = now - 60.0
        while self._user_mint_ts and self._user_mint_ts[0] < cutoff:
            self._user_mint_ts.popleft()
        if len(self._user_mint_ts) >= self.cfg.user_mints_per_minute and urgency < 1.5:
            return -1
        self._user_mint_ts.append(now)

        pid = self.codebook.mint_from_text(text, bump_dup_threshold=self.cfg.dedup_threshold)
        if pid >= 0:
            self._cache_put(self._text_cache, text, pid, self.cfg.text_cache_max)
            if self.skill_log is not None:
                self.skill_log.log_mint(pid, LAYER_L3, text, extra={
                    "source": "user",
                    "urgency": urgency,
                    "embedding_hash": _short_hash(text),
                })
        return pid

    # ------------------------------------------------------------------ AI path

    def synthesize_from_trace(
        self,
        action_trace: List[int],
        success: bool = True,
        reward: float = 0.0,
        description: str = "",
    ) -> int:
        """Mint a compound from a demonstration trace.  Returns proto_id."""
        if not action_trace:
            return -1
        if len(action_trace) < self.cfg.trace_min_len:
            return -1
        seq = list(action_trace)[: self.cfg.trace_max_len]

        # Distinguish caches by *full* description so two different labels
        # for the same trace get two different prototypes (was: cache key
        # only used `bool(description)` and ignored which description).
        cache_key = (tuple(seq), description or "")
        cached = self._cache_touch(self._trace_cache, cache_key)
        if cached is not None:
            self.codebook.activate(cached, reward=reward if success else -abs(reward))
            return cached

        pid = self.codebook.mint_from_trace(seq, description=description, success=success)
        if pid < 0:
            return pid
        self._cache_put(self._trace_cache, cache_key, pid, self.cfg.trace_cache_max)

        if self.skill_log is not None:
            self.skill_log.log_mint(
                pid,
                LAYER_L3 if description else LAYER_L2,
                description or f"trace[{','.join(str(x) for x in seq)}]",
                extra={
                    "source": "trace",
                    "success": success,
                    "reward": reward,
                    "len": len(seq),
                },
            )
        return pid

    # ------------------------------------------------------------------ goal hook

    def link_goal_to_skill(
        self,
        goal_description: str,
        goal_embedding: Optional[torch.Tensor] = None,
    ) -> int:
        """Hook for ``intrinsic.SelfGoalProposer``.

        When SelfGoalProposer suggests a sub-goal we mint a skill for
        it so the agent has a target prototype to drive toward.  Either
        the description or the embedding (or both) may be supplied.
        """
        if goal_embedding is not None:
            # Use the precomputed embedding, dedup-quering against existing.
            if goal_embedding.numel() != self.codebook.hidden:
                raise ValueError("goal_embedding dim mismatch")
            hits = self.codebook.query(goal_embedding, top_k=1)
            if hits and hits[0][2] >= self.cfg.dedup_threshold:
                pid = hits[0][0]
                self.codebook.activate(pid, reward=0.3)
                return pid
            pid = self.codebook._add_prototype(
                goal_embedding,
                layer=LAYER_L3,
                description=goal_description or "goal",
                trigger_seq=None,
                initial_strength=0.5,
            )
            if pid >= 0 and self.skill_log is not None:
                self.skill_log.log_mint(pid, LAYER_L3, goal_description, extra={"source": "self_goal"})
            return pid
        return self.synthesize_from_description(goal_description, urgency=0.8)

    # ------------------------------------------------------------------ housekeeping

    def query_similar(
        self,
        description_or_emb,
        top_k: int = 5,
    ) -> List[Tuple[int, str, float]]:
        """Return top-K (proto_id, layer, similarity) for a query."""
        if isinstance(description_or_emb, str):
            emb = self.embed_fn(description_or_emb)
        else:
            emb = description_or_emb
        return self.codebook.query(emb, top_k=top_k)

    def monthly_ltd_pass(self) -> dict:
        """Run LTD decay + (optional) archival pruning.  Idempotent."""
        decayed = self.codebook.decay_unused(days=self.cfg.decay_days)
        pruned: List[int] = []
        if self.cfg.auto_prune:
            pruned = self.codebook.prune(hard_delete=False)
        if self.skill_log is not None and pruned:
            self.skill_log.log_prune(pruned, reason="monthly_ltd")
        return {"decayed": decayed, "pruned": pruned}

    def stats(self) -> dict:
        cb_stats = self.codebook.stats()
        return {
            **cb_stats,
            "synth_text_cache": len(self._text_cache),
            "synth_trace_cache": len(self._trace_cache),
            "synth_recent_user_mints": len(self._user_mint_ts),
            "synth_cfg": {
                "dedup_threshold": self.cfg.dedup_threshold,
                "user_mints_per_minute": self.cfg.user_mints_per_minute,
                "decay_days": self.cfg.decay_days,
            },
        }


def _short_hash(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()[:12]


# ---------------------------------------------------------------------------
# Smoke
# ---------------------------------------------------------------------------


def _smoke() -> None:  # pragma: no cover - manual run
    cb = UniversalCodebook(hidden=64, K_initial=9)
    synth = SkillSynthesizer(cb)

    # 3 user-driven L3 mints
    a = synth.synthesize_from_description("查股市行情每天 9 点")
    b = synth.synthesize_from_description("打开 GitHub trending repo")
    c = synth.synthesize_from_description("在 arxiv 上搜 spiking neural net")
    print("[user mints]", a, b, c)

    # Identical request -> bump existing, no duplicate
    a2 = synth.synthesize_from_description("查股市行情每天 9 点")
    print("[bump]", a, a2, "same?", a == a2)

    # Trace mint
    pid = synth.synthesize_from_trace([0, 1, 2, 4], success=True, reward=0.8)
    pid2 = synth.synthesize_from_trace([0, 1, 2, 4], success=True, reward=0.8)
    print("[trace mints]", pid, pid2, "same?", pid == pid2)

    # LTD pass
    print("[monthly]", synth.monthly_ltd_pass())
    print("[final]", synth.stats())


if __name__ == "__main__":  # pragma: no cover
    _smoke()


__all__ = ["SkillSynthesizer", "SynthConfig"]
